name: Artifacts test
on: push
jobs:
    upload:
        runs-on: ubuntu-latest
        steps:
            - run: date > date_dayo.txt # アーティファクト作成
            - uses: actions/upload-artifact@v4
              with:
                name: uploaded_dayo
                path: date_dayo.txt
                retention-days: 3 # 保存期間ね
    download:
        runs-on: ubuntu-latest
        needs: [upload]
        steps:
            - uses: actions/download-artifact@v4
              with:
                name: uploaded_dayo # upload-artifactに指定したnameね
                path: downloaded_dayo
            - run: cat downloaded_dayo/date_dayo.txt
            