name: Cache test
on: push
jobs:
    cache:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/cache@v2
              with:
                key: test-${{ runner.os }}-${{ github.sha }}
                path: ${{ github.workspace }}/dummydayo
                restore-keys: test-${{ runner.os }}-
            - run: |
                if [[ -f "${GITHUB_WORKSPACE}/dummydayo" ]]; then exit 0; fi
                dd if=/dev/urandom of="${GITHUB_WORKSPACE}/dummydayo" bs=1M count=10
                sleep 30
            - run: ls -lh "${GITHUB_WORKSPACE}/dummydayo"
                
