name: CI Sandbox

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTOR: ${{ github.actor }}

    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          echo "${{ github.workspace }}"
          echo "${{ github.repository }}"
          echo "${{ runner.os }}"
          echo "${{ runner.arch }}"
          echo "${{ runner.temp }}"
          echo "${{ github.event_name }}"
          echo "${{ github.action }}"
          echo "${{ env.ACTOR }}"
          echo "${ACTOR}"
          
