name: github context dump toJson function
run-name: Run by @${{ github.actor }} ${{ github.event_name }} ${{ github.ref }}
on: push
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${CONTEXT}"
        env:
          CONTEXT: ${{ toJSON(github) }} 
