name: Sequential jobs example
on: push
jobs:
    first:
        runs-on: ubuntu-latest
        steps:
            - id: first
              run: |
                echo "result=firstResult" >> "${GITHUB_OUTPUT}"
        outputs:
            result: ${{ steps.first.outputs.result }}
    second:
        runs-on: ubuntu-latest
        needs: first
        steps:
            - env: FIRST_RESULT: ${{ needs.first.outputs.result }}
              run: echo "${FIRST_RESULT}"
    third:
        runs-on: ubuntu-latest
        needs: second
        steps:
            - run: sleep 3 && echo "third job"
    other:
        runs-on: ubuntu-latest
        steps:
            - run: echo "other job"
    finaly:
        runs-on: ubuntu-latest
        needs: [third, other]
        steps:
            - run: echo "finaly job"