name: Release
on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
    relase:
        runs-on: ubuntu-latest
        env:
            VERSION: ${{ github.ref_name }}
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v5
              with:
                go-version: '1.22'
            - run: |
                go build -Idflags "-X main.version=${VERSION}" \
                 -o "${RUNNER_TEMP}/example" go/example/main.go
            - run: |
                gh release create "${VERSION}" --title "${VERSION}" --generate-notes
                gh release upload "${VERSION}" "${RUNNER_TEMP}/example"
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

                

